@startuml
'https://plantuml.com/class-diagram

class Pessoa {
    + nome: CharField
    + cpf: CharField
    + email: EmailField
}

class Funcionario {
    + password: CharField
}

class Cliente {
    + credito: FloatField
}

enum Sexo {
    + MASCULINO: IntegerField
    + FEMININO: IntegerField
}

class Telefone {
    + codigoArea: CharField
    + numero: CharField
}

class Empresa {
    + cnpj: CharField
    + isMatriz: BooleanField
}

class Endereco {
    + logradouro: CharField
    + numero: IntegerField
    + complemento: CharField
    + bairro: CharField
    + cep: CharField
}

class Cidade {
    + nome: CharField
}

class Estado {
    + sigla: CharField
    + nome: CharField
}

class Fabricante {
    + razaoSocial: CharField
    + nomeFantasia: CharField
    + email: EmailFeld
    + cnpj: CharField
}

class Veiculo {
    + modelo: CharField
    + ano: CharField
    + placa: CharField
    + chassi: CharField
}

enum Tipo {
    + CARRO: IntegerField
    + CAMINHAO: IntegerField
    + PICAPE: IntegerField
}

class Servico {
    + nome: CharField
    + descricao: TextField
    + valor: FloatField
}

class OrdemServico {
    + observacao: CharField
    + dataInicio: DateTimeField
    + dataFim: DateTimeField
    + valorTotal: FloatField
}

enum Status {
    + ABERTO: IntegerField
    + EM_ANDAMENTO: IntegerField
    + FINALIZADO: IntegerField
    + CANCELADO: IntegerField
}

OrdemServico "*" o--> "1" Veiculo
OrdemServico "*" o-left-> "1" Cliente
OrdemServico "*" o--> "1" Funcionario
OrdemServico "*" o-right-> "*" Servico
OrdemServico "*" -up-> "1" Status

Veiculo "*" -up-> "1" Tipo
Veiculo "*" o-left-> "1" Fabricante

Funcionario "1" -left-> "1" Pessoa
Funcionario "*" o-right-> "1" Empresa

Cliente "1" --> "1" Pessoa
Cliente "1" *-left-> "*" Veiculo

Pessoa "1" *-down-> "*" Endereco
Pessoa "1" *--> "*" Telefone
Pessoa "*" --> "1" Sexo

Endereco "*" o-left-> "1" Cidade

Cidade "*" o-left-> "1" Estado

@enduml