# Generated by Django 5.0.6 on 2024-06-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='celular',
        ),
    ]
