# Generated by Django 5.0.6 on 2024-06-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.IntegerField(choices=[(2, 'Feminino'), (1, 'Masculino')]),
        ),
    ]
