# Generated by Django 5.0.6 on 2024-06-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cidade_estado_alter_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone',
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='telefone', to='core.pessoa'),
            preserve_default=False,
        ),
    ]
