# Generated by Django 5.0.6 on 2024-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')]),
        ),
    ]
