# Generated by Django 5.0.6 on 2024-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.IntegerField(choices=[(2, 'Feminino'), (1, 'Masculino')]),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
