# Generated by Django 5.0.6 on 2024-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(max_length=255)),
                ('dataInicial', models.DateTimeField(auto_now_add=True)),
                ('dataFinal', models.DateTimeField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(3, 'Finalizado'), (1, 'Aberto'), (2, 'Em Andamento'), (4, 'Cancelado')])),
            ],
            options={
                'db_table': 'ordemServico',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
    ]
