# Generated by Django 5.0.6 on 2024-06-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('servicos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordemServico', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordemServico', to='usuarios.funcionario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ManyToManyField(related_name='ordemServico', to='servicos.servico'),
        ),
    ]
