# Generated by Django 5.0.6 on 2024-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('servicos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (4, 'Cancelado'), (3, 'Finalizado'), (2, 'Em Andamento')]),
        ),
        migrations.RemoveField(
            model_name='servico',
            name='empresa',
        ),
        migrations.AddField(
            model_name='servico',
            name='empresa',
            field=models.ManyToManyField(related_name='servico', to='empresas.empresa'),
        ),
    ]
