# Generated by Django 5.0.6 on 2024-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_ordemservico_status_remove_servico_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em Andamento'), (4, 'Cancelado'), (3, 'Finalizado')]),
        ),
    ]
