# Generated by Django 5.0.6 on 2024-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_remove_servico_empresa_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(4, 'Cancelado'), (2, 'Em Andamento'), (3, 'Finalizado'), (1, 'Aberto')]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
