# Generated by Django 5.0.6 on 2024-06-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_ordemservico_status_alter_servico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.IntegerField(choices=[(2, 'Em Andamento'), (3, 'Finalizado'), (1, 'Aberto'), (4, 'Cancelado')]),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
