# Generated by Django 5.0.6 on 2024-06-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_tipo_alter_fabricante_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fabricante',
            table='fabricante',
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculo',
        ),
    ]
