# Generated by Django 5.0.6 on 2024-06-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_fabricante_table_alter_veiculo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fabricante',
        ),
    ]
