# Generated by Django 5.0.6 on 2024-06-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('veiculo', '0004_delete_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='empresas.fabricante'),
        ),
    ]
