# Generated by Django 5.0.6 on 2024-06-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pessoa_sexo'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to='core.endereco'),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='core.endereco'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to='core.telefone'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='telefone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='core.telefone'),
        ),
    ]
