# Generated by Django 5.0.6 on 2024-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_endereco_fabricante_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
