# Generated by Django 5.0.6 on 2024-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_fabricante_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
