# Generated by Django 5.0.6 on 2024-06-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricante',
            old_name='nomeSocial',
            new_name='nomeFantasia',
        ),
    ]
